# Generated by Django 4.2.5 on 2023-09-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
