# Generated by Django 4.2.5 on 2023-09-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_remove_listitem_done_listitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
